### ISSUE TITLE
Setting `notify_errors` to false doesn't seem to work

### ISSUE THREAD

**Issue by AndrewRadev** [vladimir-g/fainty#1]
I tried adding a `settings = { notify_errors = false }` to the instantiation of the "pulseaudio" widget, but it didn't seem to work. Looking at the source code, I think this line is the problem: https://github.com/vladimir-g/fainty/blob/master/widgets/pulseaudio.lua#L259

It seems to me like if the setting is `false` then the `or true` is going to set it to true regardless. I'm not very familiar with lua, so I'm not 100% sure about this (maybe the `or` isn't boolean?), and I'm also not sure how to check for the presence of the key without evaluating it, otherwise I would have suggested a PR. I'm currently working around this by manually editing this line.

**Comment by vladimir-g** [comment]
Thank you.

It was my stupid error, of course `X or true` will result in true every time when `X` is false, but I've just copied that pattern from other settings and never really checked usage of that setting in my config. Now it must work correctly.

**Comment by AndrewRadev** [comment]
It does work now :). Thanks a lot for the quick fix.
